### ISSUE TITLE
 routes 討論

### ISSUE THREAD

**Issue by tsai-jimmy** [tsai-jimmy/api_train_system#2]
https://github.com/tsai-jimmy/api_train_system/blob/bedac2b32af31b60febfe86c4d1933d52b1e6fdb/config/routes.rb#L3-L14

**Comment by tsai-jimmy** [comment]
``` ruby
resources :reservations, param: :booking_code, :only => [:index, :show, :create, :update, :destroy] 
```
這個我很好奇，這麼寫對嗎？ index 應該是不需要 `param: :booking_code` 的

**Comment by chenyunli6** [comment]
> ```ruby
> resources :reservations, param: :booking_code, :only => [:index, :show, :create, :update, :destroy] 
> ```
> 
> 這個我很好奇，這麼寫對嗎？ index 應該是不需要 `param: :booking_code` 的

![image](https://user-images.githubusercontent.com/20024532/72403521-4a9de680-378d-11ea-9d84-4ff9d981ff25.png)

这么写没有问题。参考：https://guides.rubyonrails.org/v5.2/routing.html#overriding-named-route-parameters
